-- Base de données :  "moviecy"

BEGIN;

-- Suppression des tables existantes

DROP TABLE IF EXISTS "movies","movie","moviecy";

-- Création de la table

CREATE TABLE "movies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" DATE NOT NULL,
  "name" TEXT NOT NULL,
  "director" TEXT NOT NULL,
  "year" INTEGER NOT NULL,
  "letterboxd_url" TEXT NOT NULL,
  "rating" DECIMAL NOT NULL,
  "tmdb_id" INTEGER,
  "overview_en" TEXT,
  "overview_fr" TEXT
);

-- Seeding

INSERT INTO "movies" (date, name, director, year, letterboxd_url, rating) VALUES
(now(),'movie title','director name','year','https://xxxxx','5'),
(now(),'movie title','director name','year','https://xxxxx','5');
-- (...)

COMMIT;